# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-07 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=500, verbose_name='title'),
        ),
    ]
